name: Deploy my Lambda Function

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-runner
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2
        with:
            python-version: 3.8
      - name: install libraries
        run: |
          cd function
          python -m pip install --upgrade pip
          if [ -f requirementes.txt ]; then pip install -r requirements.txt -t .; fi
      - name: Create zip bundle
        run: |
          cd function
          zip -r ../${{  github.sha }}.zip .
      - name: Archieve artifact
        uses: actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: ${{  github.sha }}.zip

  upload:
    runs-on: ubuntu-runner
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: zipped-bundle
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
          aws-region: us-east-1
      - name: Upload to S3
        run: aws s3 cp ${{ github.sha }}.zip s3://BUCKETNAME/${{ github.sha }}.zip
